semi: true
trailingComma: all
singleQuote: false
printWidth: 120
tabWidth: 4
useTabs: true
plugins:
    - "prettier-plugin-tailwindcss"
vueIndentScriptAndStyle: false
singleAttributePerLine: false
endOfLine: lf
bracketSpacing: true
arrowParens: always
